// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: soundbar.proto

package InstanceSoundbar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SoundbarFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trigger bool `protobuf:"varint,1,opt,name=trigger,proto3" json:"trigger,omitempty"` // 0: music off, 1: music on
}

func (x *SoundbarFrame) Reset() {
	*x = SoundbarFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soundbar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoundbarFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundbarFrame) ProtoMessage() {}

func (x *SoundbarFrame) ProtoReflect() protoreflect.Message {
	mi := &file_soundbar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundbarFrame.ProtoReflect.Descriptor instead.
func (*SoundbarFrame) Descriptor() ([]byte, []int) {
	return file_soundbar_proto_rawDescGZIP(), []int{0}
}

func (x *SoundbarFrame) GetTrigger() bool {
	if x != nil {
		return x.Trigger
	}
	return false
}

type SoundbarRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SoundbarRes) Reset() {
	*x = SoundbarRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_soundbar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoundbarRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundbarRes) ProtoMessage() {}

func (x *SoundbarRes) ProtoReflect() protoreflect.Message {
	mi := &file_soundbar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundbarRes.ProtoReflect.Descriptor instead.
func (*SoundbarRes) Descriptor() ([]byte, []int) {
	return file_soundbar_proto_rawDescGZIP(), []int{1}
}

func (x *SoundbarRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SoundbarRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_soundbar_proto protoreflect.FileDescriptor

var file_soundbar_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x62, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x22, 0x29, 0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x62, 0x61, 0x72, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0b, 0x73,
	0x6f, 0x75, 0x6e, 0x64, 0x62, 0x61, 0x72, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x55, 0x0a, 0x08, 0x53, 0x6f, 0x75, 0x6e,
	0x64, 0x62, 0x61, 0x72, 0x12, 0x49, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x2e, 0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x2e, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x62, 0x61, 0x72, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x1a, 0x1b, 0x2e, 0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x62, 0x61, 0x72, 0x52, 0x65, 0x73, 0x42,
	0x1b, 0x5a, 0x19, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x62, 0x61, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_soundbar_proto_rawDescOnce sync.Once
	file_soundbar_proto_rawDescData = file_soundbar_proto_rawDesc
)

func file_soundbar_proto_rawDescGZIP() []byte {
	file_soundbar_proto_rawDescOnce.Do(func() {
		file_soundbar_proto_rawDescData = protoimpl.X.CompressGZIP(file_soundbar_proto_rawDescData)
	})
	return file_soundbar_proto_rawDescData
}

var file_soundbar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_soundbar_proto_goTypes = []interface{}{
	(*SoundbarFrame)(nil), // 0: HOLME_instance.soundbarFrame
	(*SoundbarRes)(nil),   // 1: HOLME_instance.soundbarRes
}
var file_soundbar_proto_depIdxs = []int32{
	0, // 0: HOLME_instance.Soundbar.HandleFrame:input_type -> HOLME_instance.soundbarFrame
	1, // 1: HOLME_instance.Soundbar.HandleFrame:output_type -> HOLME_instance.soundbarRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_soundbar_proto_init() }
func file_soundbar_proto_init() {
	if File_soundbar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_soundbar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoundbarFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_soundbar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoundbarRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_soundbar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_soundbar_proto_goTypes,
		DependencyIndexes: file_soundbar_proto_depIdxs,
		MessageInfos:      file_soundbar_proto_msgTypes,
	}.Build()
	File_soundbar_proto = out.File
	file_soundbar_proto_rawDesc = nil
	file_soundbar_proto_goTypes = nil
	file_soundbar_proto_depIdxs = nil
}
