// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: refrigerator.proto

package InstanceRefrigerator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Refrigerator_HandleFrame_FullMethodName = "/HOLME_instance.Refrigerator/HandleFrame"
)

// RefrigeratorClient is the client API for Refrigerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RefrigeratorClient interface {
	HandleFrame(ctx context.Context, in *RefrigeratorFrame, opts ...grpc.CallOption) (*RefrigeratorRes, error)
}

type refrigeratorClient struct {
	cc grpc.ClientConnInterface
}

func NewRefrigeratorClient(cc grpc.ClientConnInterface) RefrigeratorClient {
	return &refrigeratorClient{cc}
}

func (c *refrigeratorClient) HandleFrame(ctx context.Context, in *RefrigeratorFrame, opts ...grpc.CallOption) (*RefrigeratorRes, error) {
	out := new(RefrigeratorRes)
	err := c.cc.Invoke(ctx, Refrigerator_HandleFrame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefrigeratorServer is the server API for Refrigerator service.
// All implementations must embed UnimplementedRefrigeratorServer
// for forward compatibility
type RefrigeratorServer interface {
	HandleFrame(context.Context, *RefrigeratorFrame) (*RefrigeratorRes, error)
	mustEmbedUnimplementedRefrigeratorServer()
}

// UnimplementedRefrigeratorServer must be embedded to have forward compatible implementations.
type UnimplementedRefrigeratorServer struct {
}

func (UnimplementedRefrigeratorServer) HandleFrame(context.Context, *RefrigeratorFrame) (*RefrigeratorRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleFrame not implemented")
}
func (UnimplementedRefrigeratorServer) mustEmbedUnimplementedRefrigeratorServer() {}

// UnsafeRefrigeratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RefrigeratorServer will
// result in compilation errors.
type UnsafeRefrigeratorServer interface {
	mustEmbedUnimplementedRefrigeratorServer()
}

func RegisterRefrigeratorServer(s grpc.ServiceRegistrar, srv RefrigeratorServer) {
	s.RegisterService(&Refrigerator_ServiceDesc, srv)
}

func _Refrigerator_HandleFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefrigeratorFrame)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefrigeratorServer).HandleFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Refrigerator_HandleFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefrigeratorServer).HandleFrame(ctx, req.(*RefrigeratorFrame))
	}
	return interceptor(ctx, in, info, handler)
}

// Refrigerator_ServiceDesc is the grpc.ServiceDesc for Refrigerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Refrigerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HOLME_instance.Refrigerator",
	HandlerType: (*RefrigeratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleFrame",
			Handler:    _Refrigerator_HandleFrame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "refrigerator.proto",
}
