// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: television.proto

package InstanceTelevision

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Television_HandleFrame_FullMethodName = "/HOLME_instance.Television/HandleFrame"
)

// TelevisionClient is the client API for Television service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelevisionClient interface {
	HandleFrame(ctx context.Context, in *TelevisionFrame, opts ...grpc.CallOption) (*TelevisionRes, error)
}

type televisionClient struct {
	cc grpc.ClientConnInterface
}

func NewTelevisionClient(cc grpc.ClientConnInterface) TelevisionClient {
	return &televisionClient{cc}
}

func (c *televisionClient) HandleFrame(ctx context.Context, in *TelevisionFrame, opts ...grpc.CallOption) (*TelevisionRes, error) {
	out := new(TelevisionRes)
	err := c.cc.Invoke(ctx, Television_HandleFrame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelevisionServer is the server API for Television service.
// All implementations must embed UnimplementedTelevisionServer
// for forward compatibility
type TelevisionServer interface {
	HandleFrame(context.Context, *TelevisionFrame) (*TelevisionRes, error)
	mustEmbedUnimplementedTelevisionServer()
}

// UnimplementedTelevisionServer must be embedded to have forward compatible implementations.
type UnimplementedTelevisionServer struct {
}

func (UnimplementedTelevisionServer) HandleFrame(context.Context, *TelevisionFrame) (*TelevisionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleFrame not implemented")
}
func (UnimplementedTelevisionServer) mustEmbedUnimplementedTelevisionServer() {}

// UnsafeTelevisionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelevisionServer will
// result in compilation errors.
type UnsafeTelevisionServer interface {
	mustEmbedUnimplementedTelevisionServer()
}

func RegisterTelevisionServer(s grpc.ServiceRegistrar, srv TelevisionServer) {
	s.RegisterService(&Television_ServiceDesc, srv)
}

func _Television_HandleFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelevisionFrame)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelevisionServer).HandleFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Television_HandleFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelevisionServer).HandleFrame(ctx, req.(*TelevisionFrame))
	}
	return interceptor(ctx, in, info, handler)
}

// Television_ServiceDesc is the grpc.ServiceDesc for Television service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Television_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HOLME_instance.Television",
	HandlerType: (*TelevisionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleFrame",
			Handler:    _Television_HandleFrame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "television.proto",
}
