// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: aircon.proto

package InstanceAircon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AirconFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trigger     bool  `protobuf:"varint,1,opt,name=trigger,proto3" json:"trigger,omitempty"` // 0: off / 1: on
	Temperature int64 `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	WindDegree  int64 `protobuf:"varint,3,opt,name=windDegree,proto3" json:"windDegree,omitempty"` // air conditioner intensity
}

func (x *AirconFrame) Reset() {
	*x = AirconFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aircon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirconFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirconFrame) ProtoMessage() {}

func (x *AirconFrame) ProtoReflect() protoreflect.Message {
	mi := &file_aircon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirconFrame.ProtoReflect.Descriptor instead.
func (*AirconFrame) Descriptor() ([]byte, []int) {
	return file_aircon_proto_rawDescGZIP(), []int{0}
}

func (x *AirconFrame) GetTrigger() bool {
	if x != nil {
		return x.Trigger
	}
	return false
}

func (x *AirconFrame) GetTemperature() int64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AirconFrame) GetWindDegree() int64 {
	if x != nil {
		return x.WindDegree
	}
	return 0
}

type AirconRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AirconRes) Reset() {
	*x = AirconRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aircon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirconRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirconRes) ProtoMessage() {}

func (x *AirconRes) ProtoReflect() protoreflect.Message {
	mi := &file_aircon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirconRes.ProtoReflect.Descriptor instead.
func (*AirconRes) Descriptor() ([]byte, []int) {
	return file_aircon_proto_rawDescGZIP(), []int{1}
}

var File_aircon_proto protoreflect.FileDescriptor

var file_aircon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x69, 0x72, 0x63, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x69,
	0x0a, 0x0b, 0x61, 0x69, 0x72, 0x63, 0x6f, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x65,
	0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x69, 0x6e,
	0x64, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x77,
	0x69, 0x6e, 0x64, 0x44, 0x65, 0x67, 0x72, 0x65, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x61, 0x69, 0x72,
	0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x32, 0x4f, 0x0a, 0x06, 0x41, 0x69, 0x72, 0x63, 0x6f, 0x6e,
	0x12, 0x45, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x2e, 0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x61, 0x69, 0x72, 0x63, 0x6f, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x19, 0x2e, 0x48,
	0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x61, 0x69,
	0x72, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x42, 0x19, 0x5a, 0x17, 0x73, 0x72, 0x63, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x69, 0x72, 0x63,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aircon_proto_rawDescOnce sync.Once
	file_aircon_proto_rawDescData = file_aircon_proto_rawDesc
)

func file_aircon_proto_rawDescGZIP() []byte {
	file_aircon_proto_rawDescOnce.Do(func() {
		file_aircon_proto_rawDescData = protoimpl.X.CompressGZIP(file_aircon_proto_rawDescData)
	})
	return file_aircon_proto_rawDescData
}

var file_aircon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aircon_proto_goTypes = []interface{}{
	(*AirconFrame)(nil), // 0: HOLME_instance.airconFrame
	(*AirconRes)(nil),   // 1: HOLME_instance.airconRes
}
var file_aircon_proto_depIdxs = []int32{
	0, // 0: HOLME_instance.Aircon.HandleFrame:input_type -> HOLME_instance.airconFrame
	1, // 1: HOLME_instance.Aircon.HandleFrame:output_type -> HOLME_instance.airconRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aircon_proto_init() }
func file_aircon_proto_init() {
	if File_aircon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aircon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirconFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aircon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirconRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aircon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aircon_proto_goTypes,
		DependencyIndexes: file_aircon_proto_depIdxs,
		MessageInfos:      file_aircon_proto_msgTypes,
	}.Build()
	File_aircon_proto = out.File
	file_aircon_proto_rawDesc = nil
	file_aircon_proto_goTypes = nil
	file_aircon_proto_depIdxs = nil
}
