// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: lightbulb.proto

package lightblub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LightBulbFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trigger bool   `protobuf:"varint,1,opt,name=trigger,proto3" json:"trigger,omitempty"` //* true: on, false: off
	Degree  int64  `protobuf:"varint,2,opt,name=degree,proto3" json:"degree,omitempty"`
	Color   string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *LightBulbFrame) Reset() {
	*x = LightBulbFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lightbulb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightBulbFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightBulbFrame) ProtoMessage() {}

func (x *LightBulbFrame) ProtoReflect() protoreflect.Message {
	mi := &file_lightbulb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightBulbFrame.ProtoReflect.Descriptor instead.
func (*LightBulbFrame) Descriptor() ([]byte, []int) {
	return file_lightbulb_proto_rawDescGZIP(), []int{0}
}

func (x *LightBulbFrame) GetTrigger() bool {
	if x != nil {
		return x.Trigger
	}
	return false
}

func (x *LightBulbFrame) GetDegree() int64 {
	if x != nil {
		return x.Degree
	}
	return 0
}

func (x *LightBulbFrame) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type LightBulbRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LightBulbRes) Reset() {
	*x = LightBulbRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lightbulb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightBulbRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightBulbRes) ProtoMessage() {}

func (x *LightBulbRes) ProtoReflect() protoreflect.Message {
	mi := &file_lightbulb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightBulbRes.ProtoReflect.Descriptor instead.
func (*LightBulbRes) Descriptor() ([]byte, []int) {
	return file_lightbulb_proto_rawDescGZIP(), []int{1}
}

var File_lightbulb_proto protoreflect.FileDescriptor

var file_lightbulb_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x62, 0x75, 0x6c, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x62, 0x6c, 0x75, 0x62, 0x22, 0x58, 0x0a, 0x0e,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x42, 0x75, 0x6c, 0x62, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x67, 0x72,
	0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x0e, 0x0a, 0x0c, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x42,
	0x75, 0x6c, 0x62, 0x52, 0x65, 0x73, 0x32, 0x4e, 0x0a, 0x09, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x42,
	0x75, 0x6c, 0x62, 0x12, 0x41, 0x0a, 0x0b, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x12, 0x19, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x62, 0x6c, 0x75, 0x62, 0x2e, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x42, 0x75, 0x6c, 0x62, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x17, 0x2e,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x62, 0x6c, 0x75, 0x62, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x42,
	0x75, 0x6c, 0x62, 0x52, 0x65, 0x73, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x62, 0x6c, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lightbulb_proto_rawDescOnce sync.Once
	file_lightbulb_proto_rawDescData = file_lightbulb_proto_rawDesc
)

func file_lightbulb_proto_rawDescGZIP() []byte {
	file_lightbulb_proto_rawDescOnce.Do(func() {
		file_lightbulb_proto_rawDescData = protoimpl.X.CompressGZIP(file_lightbulb_proto_rawDescData)
	})
	return file_lightbulb_proto_rawDescData
}

var file_lightbulb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lightbulb_proto_goTypes = []interface{}{
	(*LightBulbFrame)(nil), // 0: lightblub.lightBulbFrame
	(*LightBulbRes)(nil),   // 1: lightblub.lightBulbRes
}
var file_lightbulb_proto_depIdxs = []int32{
	0, // 0: lightblub.LightBulb.handleFrame:input_type -> lightblub.lightBulbFrame
	1, // 1: lightblub.LightBulb.handleFrame:output_type -> lightblub.lightBulbRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lightbulb_proto_init() }
func file_lightbulb_proto_init() {
	if File_lightbulb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lightbulb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightBulbFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lightbulb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightBulbRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lightbulb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lightbulb_proto_goTypes,
		DependencyIndexes: file_lightbulb_proto_depIdxs,
		MessageInfos:      file_lightbulb_proto_msgTypes,
	}.Build()
	File_lightbulb_proto = out.File
	file_lightbulb_proto_rawDesc = nil
	file_lightbulb_proto_goTypes = nil
	file_lightbulb_proto_depIdxs = nil
}
