// HIVEMIND
// GENERATED PROTOBUF FILE

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: merged.proto

package hivemind

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurtainFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsHorizontal bool `protobuf:"varint,1,opt,name=isHorizontal,proto3" json:"isHorizontal,omitempty"` // 0: vertical, 1: horizontal
	IsCenterMode bool `protobuf:"varint,2,opt,name=isCenterMode,proto3" json:"isCenterMode,omitempty"` // 0: side to side mode, 1: center mode
	// 0 & horizontal: opened from right / 1 & horizontal: opened from left
	// 0 & vertical: opened from down / 1 & vertical: opened from top
	IsLeftOrTop bool  `protobuf:"varint,3,opt,name=isLeftOrTop,proto3" json:"isLeftOrTop,omitempty"`
	Degree      int64 `protobuf:"varint,4,opt,name=degree,proto3" json:"degree,omitempty"` // 0 - 100: how much curtains are drawn
}

func (x *CurtainFrame) Reset() {
	*x = CurtainFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurtainFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurtainFrame) ProtoMessage() {}

func (x *CurtainFrame) ProtoReflect() protoreflect.Message {
	mi := &file_merged_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurtainFrame.ProtoReflect.Descriptor instead.
func (*CurtainFrame) Descriptor() ([]byte, []int) {
	return file_merged_proto_rawDescGZIP(), []int{0}
}

func (x *CurtainFrame) GetIsHorizontal() bool {
	if x != nil {
		return x.IsHorizontal
	}
	return false
}

func (x *CurtainFrame) GetIsCenterMode() bool {
	if x != nil {
		return x.IsCenterMode
	}
	return false
}

func (x *CurtainFrame) GetIsLeftOrTop() bool {
	if x != nil {
		return x.IsLeftOrTop
	}
	return false
}

func (x *CurtainFrame) GetDegree() int64 {
	if x != nil {
		return x.Degree
	}
	return 0
}

type CurtainRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CurtainRes) Reset() {
	*x = CurtainRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurtainRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurtainRes) ProtoMessage() {}

func (x *CurtainRes) ProtoReflect() protoreflect.Message {
	mi := &file_merged_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurtainRes.ProtoReflect.Descriptor instead.
func (*CurtainRes) Descriptor() ([]byte, []int) {
	return file_merged_proto_rawDescGZIP(), []int{1}
}

func (x *CurtainRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CurtainRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LightBulbFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trigger bool   `protobuf:"varint,1,opt,name=trigger,proto3" json:"trigger,omitempty"` //* true: on, false: off
	Degree  int64  `protobuf:"varint,2,opt,name=degree,proto3" json:"degree,omitempty"`
	Color   string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *LightBulbFrame) Reset() {
	*x = LightBulbFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightBulbFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightBulbFrame) ProtoMessage() {}

func (x *LightBulbFrame) ProtoReflect() protoreflect.Message {
	mi := &file_merged_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightBulbFrame.ProtoReflect.Descriptor instead.
func (*LightBulbFrame) Descriptor() ([]byte, []int) {
	return file_merged_proto_rawDescGZIP(), []int{2}
}

func (x *LightBulbFrame) GetTrigger() bool {
	if x != nil {
		return x.Trigger
	}
	return false
}

func (x *LightBulbFrame) GetDegree() int64 {
	if x != nil {
		return x.Degree
	}
	return 0
}

func (x *LightBulbFrame) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type LightBulbRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *LightBulbRes) Reset() {
	*x = LightBulbRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_merged_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightBulbRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightBulbRes) ProtoMessage() {}

func (x *LightBulbRes) ProtoReflect() protoreflect.Message {
	mi := &file_merged_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightBulbRes.ProtoReflect.Descriptor instead.
func (*LightBulbRes) Descriptor() ([]byte, []int) {
	return file_merged_proto_rawDescGZIP(), []int{3}
}

func (x *LightBulbRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *LightBulbRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_merged_proto protoreflect.FileDescriptor

var file_merged_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x90,
	0x01, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x69, 0x73, 0x48, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x48, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e,
	0x74, 0x61, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4d,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x4c, 0x65, 0x66,
	0x74, 0x4f, 0x72, 0x54, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x4c, 0x65, 0x66, 0x74, 0x4f, 0x72, 0x54, 0x6f, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x67,
	0x72, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65,
	0x65, 0x22, 0x3a, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x58, 0x0a,
	0x0e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x42, 0x75, 0x6c, 0x62, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x67,
	0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x0c, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x42, 0x75, 0x6c, 0x62, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x52, 0x0a, 0x07, 0x43, 0x75, 0x72, 0x74, 0x61, 0x69, 0x6e,
	0x12, 0x47, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x2e, 0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x63, 0x75, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x1a, 0x2e,
	0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x63,
	0x75, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x32, 0x58, 0x0a, 0x09, 0x4c, 0x69, 0x67,
	0x68, 0x74, 0x42, 0x75, 0x6c, 0x62, 0x12, 0x4b, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x2e, 0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x42, 0x75, 0x6c, 0x62,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x1c, 0x2e, 0x48, 0x4f, 0x4c, 0x4d, 0x45, 0x5f, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x42, 0x75, 0x6c, 0x62,
	0x52, 0x65, 0x73, 0x42, 0x13, 0x5a, 0x11, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x68, 0x69, 0x76, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_merged_proto_rawDescOnce sync.Once
	file_merged_proto_rawDescData = file_merged_proto_rawDesc
)

func file_merged_proto_rawDescGZIP() []byte {
	file_merged_proto_rawDescOnce.Do(func() {
		file_merged_proto_rawDescData = protoimpl.X.CompressGZIP(file_merged_proto_rawDescData)
	})
	return file_merged_proto_rawDescData
}

var file_merged_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_merged_proto_goTypes = []interface{}{
	(*CurtainFrame)(nil),   // 0: HOLME_instance.curtainFrame
	(*CurtainRes)(nil),     // 1: HOLME_instance.curtainRes
	(*LightBulbFrame)(nil), // 2: HOLME_instance.lightBulbFrame
	(*LightBulbRes)(nil),   // 3: HOLME_instance.lightBulbRes
}
var file_merged_proto_depIdxs = []int32{
	0, // 0: HOLME_instance.Curtain.HandleFrame:input_type -> HOLME_instance.curtainFrame
	2, // 1: HOLME_instance.LightBulb.HandleFrame:input_type -> HOLME_instance.lightBulbFrame
	1, // 2: HOLME_instance.Curtain.HandleFrame:output_type -> HOLME_instance.curtainRes
	3, // 3: HOLME_instance.LightBulb.HandleFrame:output_type -> HOLME_instance.lightBulbRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_merged_proto_init() }
func file_merged_proto_init() {
	if File_merged_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_merged_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurtainFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurtainRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightBulbFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_merged_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightBulbRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_merged_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_merged_proto_goTypes,
		DependencyIndexes: file_merged_proto_depIdxs,
		MessageInfos:      file_merged_proto_msgTypes,
	}.Build()
	File_merged_proto = out.File
	file_merged_proto_rawDesc = nil
	file_merged_proto_goTypes = nil
	file_merged_proto_depIdxs = nil
}
